name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Generate LaTeX data from YAML
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing root directory:"
          ls -la
          echo "Checking if data.yaml exists:"
          ls -la data.yaml || echo "data.yaml not found!"
          
          echo "Generating CV data..."
          cd ./src/cv
          echo "In CV directory: $(pwd)"
          ls -la
          python yaml_to_latex.py ../../data.yaml cv > cvdata.tex
          echo "CV data generated, checking cvdata.tex:"
          ls -la cvdata.tex
          head -5 cvdata.tex
          cd ../../
            echo "Generating cover letter data..."
          cd ./src/cover-letter
          echo "In cover letter directory: $(pwd)"
          ls -la
          python yaml_to_latex.py ../../data.yaml cover-letter > coverletterdata.tex
          echo "Cover letter data generated, checking coverletterdata.tex:"
          ls -la coverletterdata.tex
          head -5 coverletterdata.tex
          cd ../../
          
          echo "Final check - listing all generated files:"
          echo "CV directory:"
          ls -la ./src/cv/cvdata.tex
          echo "Cover letter directory:"
          ls -la ./src/cover-letter/coverletterdata.tex
      
      - name: Compile CV LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ./src/cv/
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: ../../static/font/*.otf
      
      - name: Compile Cover Letter LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ./src/cover-letter/
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: ../../static/font/*.otf
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            ./src/cv/main.pdf
            ./src/cover-letter/main.pdf