name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Generate LaTeX data from YAML
        run: |
          cd ./src/cv
          python yaml_to_latex.py ../../data.yaml cv > cvdata.tex
          cd ../cover-letter
          python yaml_to_latex.py ../../data.yaml cover-letter > coverletterdata.tex
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ./src/cv/main.tex
            ./src/cover-letter/main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            ./static/font/*.ttf
            ./static/font/*.otf
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            ./src/cv/main.pdf
            ./src/cover-letter/main.pdf
